### ISSUE TITLE
Question: Convert Files to mp3?

### ISSUE THREAD

**Issue by hisaac** [Osmose/moseamp#6]
Hello!

First off, thank you for this app. I've got a small collection of miniusf files that I've wanted to try playing for the longest time, but have never found an app to do it with.

This question isn't directly related to moseamp, but is indirectly. Do you know of a good way to convert these files to something more widely supported, like mp3 or wav, etc.? I've tried to find methods online, but haven't found anything yet that works.

**Comment by Osmose** [comment]
Thanks for the kind words! The easiest way I know of is to play the file back in Winamp (using [Chipamp](https://www.chipamp.org/) or something) and set the output device to the Disk Writer plugin (it should be included by default). When you play sound, instead of playing it, it should write it to a file on disk.

On MacOS there's a few projects like [Soundflower](https://github.com/mattingalls/Soundflower) that add output devices that route audio back to an input device, and you can record that input device in [Audacity](https://www.audacityteam.org/) or something while playing the files back with Moseamp.

Maybe someday Moseamp should have a proper preferences UI with a way to select an output device that includes a file writer plugin, but for now I'll close the issue since there's not much to change in Moseamp. Let me if either of those solutions above works!

**Comment by hisaac** [comment]
Thanks! I'll give the Winamp method a try and see what I can figure out.
